### ISSUE TITLE
WebAssembly support in firefox in the demo

### ISSUE THREAD

**Issue by michallepicki** [davidMcneil/the-rusty-web#1]
```Warning: Native WebAssembly support is not available in this browser, but you can still run the JavaScript and asm.js implementations.```
I am using Firefox Developer Edition 53.0a2 (2017-03-07) (64 bit).

**Comment by vladikoff** [comment]
As mentioned in https://news.ycombinator.com/item?id=13820627

> The binary has version 0xD, the last pre-release version of WebAssembly. Firefox and Chrome are now looking for version 0x1.

Needs to be fixed up
