### ISSUE TITLE
Don't use transmute!

### ISSUE THREAD

**Issue by steveklabnik** [davidMcneil/the-rusty-web#2]
Hey there! I wanted to send you a PR, but couldn't find the text of the gitbook, so I'll just open an issue. 

in https://davidmcneil.gitbooks.io/the-rusty-web/content/counter-example.html

this code is better written as

```rust
#[no_mangle]
unsafe pub extern "C" fn counter_destroy(counter: *mut Counter) {
    Box::from_raw(counter)
}

#[no_mangle]
pub extern "C" fn counter_create() -> *mut Counter {
    Box::into_raw(Box::new(Counter::new()))
}
```

That is, `from_raw`/`into_raw` over `transmute`, and the unsafety only belongs on `counter_destroy`; if you did a null check inside of it, you could make it safe too.

Very interesting guide, thanks for sharing it!

**Comment by davidMcneil** [comment]
Thank you for the feedback! That is a much better method.

And thank you for all you do in the Rust community. The books specifically are amazing!
