### ISSUE TITLE
Try replacing powi(2) with a simple multiplication.

### ISSUE THREAD

**Issue by dmitshur** [davidMcneil/the-rusty-web#3]
You wrote:

> However, if you have any insight into the poor performance, issues and pull requests are always welcome!

Here's a suggestion you can try. You're currently using `powi(2)` to multiply a number by itself in a hot loop:

https://github.com/davidMcneil/the-rusty-web/blob/84ec53a8e9d024f662e917aa5dea1f79f954f90d/src/kmeans.rs#L10

As sunfish said in a [HN comment](https://news.ycombinator.com/item?id=13820619), there's an issue https://github.com/kripken/emscripten-fastcomp/issues/171 in Emscripten where performance for small integer special cases is suboptimal.

Until that issue is resolved, why don't you just try to manually optimize the code by replacing `powi(2)` with a simple multiplication, and see how much of an effect it has? I think it's interesting to see what'll happen to the native Rust performance, as well as Rust compiled to WebAssembly performance.

**Comment by davidMcneil** [comment]
Thank you! That is exactly the kind of feedback I was hoping for. I made the change you suggested and it improved performance dramatically. I am working on writing up a new benchmarks section.

**Comment by dmitshur** [comment]
Nice, I was expecting/hoping to hear that! Looking forward to reading that update.

I ran into a very similar situation in the past, which resulted in [this blog post](https://medium.com/gopherjs/surprises-in-gopherjs-performance-4a0a49b04ecd#.pku1bqc17), in case you're curious.
