### ISSUE TITLE
cargo

### ISSUE THREAD

**Issue by liborty** [davidMcneil/the-rusty-web#4]
Hi, I tried to compile with:
~/rustprojects/rustyweb$ cargo build --release --target wasm32-unknown-emscripten
and I get the following error:
...........
Downloading num-rational v0.1.36
invalid configuration for key `target.wasm32-unknown-emscripten.rustflags`
expected a table, but found a array in rustprojects/rustyweb/.cargo/config

Any ideas what is going wrong?

**Comment by davidMcneil** [comment]
Thanks for your interest in the project. Here are a few thoughts:

- What version of the rust compiler are you using? I would recommend Rust nightly and would make sure you are updated `rustup update`?

- Do you have the Emscripten toolchain installed as outlined [here](https://davidmcneil.gitbooks.io/the-rusty-web/content/setup-and-hello-world.html). What version do you have (`emcc --version`)? It should be 1.37.0 or greater? Are you able to compile the hello world example from that link?

- Are you able to build and run the project natively `cargo run`?

- Are you able to build the project targetting asm.js `cargo build --release --target asmjs-unknown-emscripten`?

- What OS are you using? I have only tested it on Ubuntu 16.04 although I imagine others should work.

Let me know how it goes.

**Comment by liborty** [comment]
Hi David, thanks for the quick reply. Sorry, I am just a beginner and
the clang is not set in my path. Do I have to source the set emscripten
environment shell every time?
Regards, Libor

**Comment by davidMcneil** [comment]
Yes, you will have to source Emscripten every time you want to target asm.js or WebAssembly. You should be able to run `emcc --version` to verify that cargo can access the toolchain in the current shell.

You could add something like `source /path/to/emsdk_portable/emsdk_env.sh > /dev/null` to your `.bashrc` file so you did not have to source it every time.

**Comment by davidMcneil** [comment]
I am going to close this for now. I am happy to answer any other questions if you are still running into issues.
